### ISSUE TITLE
Difference in contributions

### ISSUE THREAD

**Issue by dcshzj** [CS2102-AY2021-S1-G17/CS2102_2021_S1_Team17#3]
I will be grading your project. Here is the report generated for your project: https://dcshzj.github.io/cs2102-project/

Any reason why there is a large difference in the amount of contributions?

Also, who is Wang Ziyun? I don't see any contributions made, please show me some contributions that this person has made.

Thank you.

**Comment by Yiping-Z** [comment]
Hi,
The numbers of lines in RepoSense contributions might not truly reflect all we have done.
Specifically, for Wang Ziyun, she was in charged of most the sql code and part of the report, specially, most of the code under sql folder was written by her, and we uploaded them to GitHub.
For Chen Yongyan, he was in charge of some of sql code, parts of the backend code, as well as report writing.
Hope this clarifies.

Thanks

**Comment by wzy-ziyun** [comment]
Hi, 
This is Ziyun. Sorry for causing such confusion. I was not familiar with GitHub and asked my teammates for help in pushing my code up because I was scared of the potential misoperation from my side. For your reference, we also wrote our contributions in the report.
Thank you.

**Comment by dcshzj** [comment]
> For Chen Yongyan, he was in charge of some of sql code, parts of the backend code, as well as report writing.

Can I confirm that this statement is referring to the files `routes/pet_owner.js`, `views/pet_owner/po_bid.ejs` and `views/pet_owner/po_pets_profile.ejs`?

**Comment by Raymond0212** [comment]
> > For Chen Yongyan, he was in charge of some of sql code, parts of the backend code, as well as report writing.
> 
> Can I confirm that this statement is referring to the files `routes/pet_owner.js`, `views/pet_owner/po_bid.ejs` and `views/pet_owner/po_pets_profile.ejs`?

I worked on the `routes/pet_owner.js`, `sql/init.sql` and a few parts in `views/pet_owner/po_bid.ejs` and `views/pet_owner/po_pets_profile.ejs`.

**Comment by dcshzj** [comment]
Okay I will take note of this when grading. Thanks.
